name: Auto Update

on:
  push:

jobs:
  versions:
    runs-on: ubuntu-latest

    name: Get Versions

    outputs:
      current: ${{ steps.current-version.outputs.content }}
      latest: ${{ steps.latest-version.outputs.tag }}

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - id: current-version
      name: Get current Primer Octicons version
      uses: juliangruber/read-file-action@v1
      with:
        trim: true
        path: ./.version

    - id: latest-version
      name: Get latest Primer Octicons version
      uses: oprypin/find-latest-tag@v1
      with:
        repository: primer/octicons
        regex: '^v\d+\.\d+\.\d+$'

    - name: Output versions
      run: |
        echo "Current release: ${{ steps.current-version.outputs.content }}"
        echo "Latest release: ${{ steps.latest-version.outputs.tag }}"

  update:
    runs-on: ubuntu-latest

    name: Update Primer Octicons

    needs: [versions]

    if: needs.versions.outputs.current != needs.versions.outputs.latest

    env:
      CURRENT_VERSION: ${{ needs.versions.outputs.current }}
      LATEST_VERSION: ${{ needs.versions.outputs.latest }}
      BRANCH: feature/update-${{ needs.versions.outputs.latest }}

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0
        tools: composer
        coverage: none

    - name: Install Dependencies
      run: composer update --prefer-stable --no-interaction --prefer-dist --no-progress --ansi

    -

        name: Checkout dependent repo
        uses: actions/checkout@v3
        with:
          repository: primer/octicons
          ref: ${{ env.LATEST_VERSION }}
          path: ./dist

    - name: Compile icons to resources directory
      run: ./vendor/bin/blade-icons-generate

    - name: Update version in ".version"
      run: echo ${{ env.LATEST_VERSION }}>./.version

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        push: false
        message: "chore: update to Primer Octicons v${{ env.LATEST_VERSION }}"
        author_name: GitHub Actions
        author_email: noreply@github.com

    - name: Create PR for latest version
      uses: peter-evans/create-pull-request@v3
      with:
        title: "chore: update to Primer Octicons ${{ env.LATEST_VERSION }}"
        body: |
          This updates from [${{ env.CURRENT_VERSION }}](https://github.com/primer/octicons/releases/tag/${{ env.CURRENT_VERSION }}) to [${{ env.LATEST_VERSION }}](https://github.com/primer/octicons/releases/tag/${{ env.LATEST_VERSION }}).

          Check out the differences: [`${{ env.CURRENT_VERSION }}` ... `${{ env.LATEST_VERSION }}`](https://github.com/primer/octicons/compare/${{ env.CURRENT_VERSION }}...${{ env.LATEST_VERSION }})

          Please check for any breaking or notable changes before merging.
          - [Changelog](https://github.com/primer/octicons/blob/${{ env.LATEST_VERSION }}/CHANGELOG.md#change-log)

          Please also check that the snapshots were updated successfully in commit: ${{ steps.commit_snapshots.outputs.commit_long_sha }}.
